// Auto-generated by update_stats.py — do not edit manually
var ROSTER_DATA = {
  "updated": "2026-04-02T12:04:29.594805",
  "season": "2025-26",
  "nba": [],
  "gleague": [],
  "college": [
    {
      "name": "Devin Brown",
      "position": "Guard",
      "school": "Davidson",
      "type": "college",
      "espn_id": 5311849,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5311849.png",
      "headshot_local": "images/players/devin-brown.png",
      "ig": "_devinbrown",
      "stats": {
        "ppg": 6.4,
        "rpg": 3.4,
        "apg": 1.6,
        "fg_pct": 40.8,
        "gp": 34
      }
    },
    {
      "name": "Akai Fleming",
      "position": "Guard",
      "school": "Georgia Tech",
      "type": "college",
      "espn_id": 5101784,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5101784.png",
      "headshot_local": "images/players/akai-fleming.png",
      "ig": "akai.fleming",
      "stats": {
        "ppg": 10.4,
        "rpg": 3.2,
        "apg": 1.3,
        "fg_pct": 37.3,
        "gp": 30
      }
    },
    {
      "name": "Jaiden Glover-Toscano",
      "position": "Guard",
      "school": "Saint Joseph's",
      "type": "college",
      "espn_id": 5142608,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5142608.png",
      "headshot_local": "images/players/jaiden-glover-toscano.png",
      "ig": "jglove.11",
      "stats": {
        "ppg": 15.7,
        "rpg": 4.8,
        "apg": 1.0,
        "fg_pct": 41.8,
        "gp": 34
      }
    },
    {
      "name": "Meechie Johnson Jr.",
      "position": "Guard",
      "school": "South Carolina",
      "type": "college",
      "espn_id": 4710770,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/4710770.png",
      "headshot_local": "images/players/meechie-johnson-jr.png",
      "ig": "meechie.1",
      "stats": {
        "ppg": 17.2,
        "rpg": 3.3,
        "apg": 4.3,
        "fg_pct": 41.4,
        "gp": 32
      }
    },
    {
      "name": "Kok Yat",
      "position": "Forward",
      "school": "",
      "type": "college",
      "headshot_local": "images/players/kok-yat.png",
      "ig": "tuloww.21",
      "stats": null
    },
    {
      "name": "Jaron Saulsberry",
      "position": "Forward",
      "school": "Ole Miss Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Ole Miss",
      "headshot_local": "images/players/jaron-saulsberry.jpg",
      "ig": "guard_upronny",
      "stats": null
    },
    {
      "name": "Kayden Allen",
      "position": "Guard",
      "school": "UNCOMMITTED",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "UNCOMMITTED",
      "headshot_local": "images/players/kayden-allen.jpg",
      "ig": "kaydenallennn",
      "stats": null
    },
    {
      "name": "Gallagher Placide",
      "position": "Forward",
      "school": "Wake Forest Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Wake Forest",
      "headshot_local": "images/players/gallagher-placide.jpg",
      "ig": "gallagherplacide",
      "stats": null
    },
    {
      "name": "Gavin Placide",
      "position": "Forward",
      "school": "Wake Forest Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Wake Forest",
      "headshot_local": "images/players/gavin-placide.jpg",
      "ig": "gavinplacide",
      "stats": null
    }
  ],
  "international": [
    {
      "name": "Kamar Baldwin",
      "position": "Guard",
      "team": "FC Bayern Munich",
      "league": "BBL / EuroLeague",
      "headshot_local": "images/players/kamar-baldwin.png",
      "ig": "kamar_baldwin",
      "stats": null
    },
    {
      "name": "Kobi Simmons",
      "position": "Guard",
      "team": "Saski Baskonia",
      "league": "Liga ACB / EuroLeague",
      "headshot_local": "images/players/kobi-simmons.png",
      "ig": "kobi_simmons2",
      "stats": null
    },
    {
      "name": "Kaiser Gates",
      "position": "Forward",
      "team": "UCAM Murcia",
      "league": "Liga ACB",
      "headshot_local": "images/players/kaiser-gates.png",
      "ig": "kaiserg_22",
      "stats": null
    },
    {
      "name": "Jakarr Sampson",
      "position": "Forward",
      "team": "Zhejiang Guangsha Lions",
      "league": "CBA",
      "headshot_local": "images/players/jakarr-sampson.png",
      "ig": "karrsampson14",
      "stats": null
    }
  ]
};
