// Auto-generated by update_stats.py — do not edit manually
var ROSTER_DATA = {
  "updated": "2026-02-24T16:21:18.536929",
  "season": "2025-26",
  "nba": [
    {
      "id": 1630228,
      "name": "Jonathan Kuminga",
      "position": "F",
      "team": "Atlanta Hawks",
      "team_city": "Atlanta",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630228.png",
      "headshot_local": "images/players/jonathan-kuminga.png",
      "ig": "jonathan_kuminga",
      "stats": {
        "ppg": 12.1,
        "rpg": 5.9,
        "apg": 2.5,
        "fg_pct": 45.4,
        "gp": 20
      },
      "gleague_stats": null
    },
    {
      "id": 1630625,
      "name": "Dalano Banton",
      "position": "F",
      "team": "Boston Celtics",
      "team_city": "Boston",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630625.png",
      "headshot_local": "images/players/dalano-banton.png",
      "ig": "_dubberdon",
      "stats": {
        "ppg": 3.0,
        "rpg": 0.5,
        "apg": 1.0,
        "fg_pct": 75.0,
        "gp": 2
      },
      "gleague_stats": {
        "ppg": 24.1,
        "rpg": 4.1,
        "apg": 6.7,
        "fg_pct": 44.1,
        "gp": 32,
        "team_abbr": "TEX"
      }
    },
    {
      "id": 1631169,
      "name": "Josh Minott",
      "position": "F",
      "team": "Brooklyn Nets",
      "team_city": "Brooklyn",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1631169.png",
      "headshot_local": "images/players/josh-minott.png",
      "ig": "jday.8",
      "stats": {
        "ppg": 5.8,
        "rpg": 3.6,
        "apg": 1.0,
        "fg_pct": 50.7,
        "gp": 33
      },
      "gleague_stats": null
    },
    {
      "id": 1631217,
      "name": "Moussa Diabate",
      "position": "F",
      "team": "Charlotte Hornets",
      "team_city": "Charlotte",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1631217.png",
      "headshot_local": "images/players/moussa-diabate.png",
      "ig": "m0ussadiabate",
      "stats": {
        "ppg": 8.2,
        "rpg": 8.6,
        "apg": 1.6,
        "fg_pct": 63.2,
        "gp": 50
      },
      "gleague_stats": null
    },
    {
      "id": 1630544,
      "name": "Tre Mann",
      "position": "G",
      "team": "Charlotte Hornets",
      "team_city": "Charlotte",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630544.png",
      "headshot_local": "images/players/tre-mann.png",
      "ig": "treshaunmann",
      "stats": {
        "ppg": 6.9,
        "rpg": 2.2,
        "apg": 2.1,
        "fg_pct": 36.0,
        "gp": 37
      },
      "gleague_stats": null
    },
    {
      "id": 1641772,
      "name": "Nae'Qwan Tomlin",
      "position": "F",
      "team": "Cleveland Cavaliers",
      "team_city": "Cleveland",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1641772.png",
      "headshot_local": "images/players/naeqwan-tomlin.png",
      "ig": "nae_ratty",
      "stats": {
        "ppg": 6.4,
        "rpg": 3.1,
        "apg": 0.9,
        "fg_pct": 48.0,
        "gp": 46
      },
      "gleague_stats": null
    },
    {
      "id": 1642939,
      "name": "Miles Kelly",
      "position": "G",
      "team": "Dallas Mavericks",
      "team_city": "Dallas",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1642939.png",
      "headshot_local": "images/players/miles-kelly.png",
      "ig": "miles5kelly",
      "stats": {
        "ppg": 2.8,
        "rpg": 1.6,
        "apg": 0.7,
        "fg_pct": 39.4,
        "gp": 12
      },
      "gleague_stats": {
        "ppg": 19.9,
        "rpg": 5.0,
        "apg": 2.4,
        "fg_pct": 41.6,
        "gp": 26,
        "team_abbr": "TEX"
      }
    },
    {
      "id": 1641803,
      "name": "Tristen Newton",
      "position": "G",
      "team": "Houston Rockets",
      "team_city": "Houston",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1641803.png",
      "headshot_local": "images/players/tristen-newton.png",
      "ig": "tristenewton",
      "stats": {
        "ppg": 0.4,
        "rpg": 0.5,
        "apg": 0.3,
        "fg_pct": 12.5,
        "gp": 8
      },
      "gleague_stats": {
        "ppg": 25.7,
        "rpg": 4.9,
        "apg": 5.8,
        "fg_pct": 48.2,
        "gp": 36,
        "team_abbr": "TOT"
      }
    },
    {
      "id": 1642352,
      "name": "Keshad Johnson",
      "position": "F",
      "team": "Miami Heat",
      "team_city": "Miami",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1642352.png",
      "headshot_local": "images/players/keshad-johnson.png",
      "ig": "kj_showtime0",
      "stats": {
        "ppg": 3.2,
        "rpg": 1.9,
        "apg": 0.1,
        "fg_pct": 41.3,
        "gp": 23
      },
      "gleague_stats": null
    }
  ],
  "gleague": [
    {
      "id": 1641771,
      "name": "Jalen Slawson",
      "position": "Forward",
      "team": "Birmingham Squadron",
      "team_abbr": "NOB",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1641771.png",
      "headshot_local": "images/players/jalen-slawson.png",
      "ig": "jalenslawson",
      "stats": {
        "ppg": 18.8,
        "rpg": 7.2,
        "apg": 5.3,
        "fg_pct": 48.6,
        "gp": 35,
        "team_abbr": "NOB"
      }
    },
    {
      "id": 1641746,
      "name": "Coleman Hawkins",
      "position": "Forward",
      "team": "Grand Rapids Gold",
      "team_abbr": "GRG",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1641746.png",
      "headshot_local": "images/players/coleman-hawkins.png",
      "ig": "colemanhawkins33",
      "stats": {
        "ppg": 7.3,
        "rpg": 6.1,
        "apg": 5.1,
        "fg_pct": 49.3,
        "gp": 35,
        "team_abbr": "GRG"
      }
    },
    {
      "id": 1630835,
      "name": "LJ Figueroa",
      "position": "Forward",
      "team": "Mexico City Capitanes",
      "team_abbr": "MXC",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630835.png",
      "headshot_local": "images/players/lj-figueroa.png",
      "ig": "l_comeup",
      "stats": {
        "ppg": 13.1,
        "rpg": 4.8,
        "apg": 2.1,
        "fg_pct": 54.7,
        "gp": 32,
        "team_abbr": "MXC"
      }
    },
    {
      "id": 1630227,
      "name": "Daishen Nix",
      "position": "Guard",
      "team": "Rio Grande Valley Vipers",
      "team_abbr": "RGV",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630227.png",
      "headshot_local": "images/players/daishen-nix.png",
      "ig": "djdaishen",
      "stats": {
        "ppg": 22.9,
        "rpg": 7.1,
        "apg": 7.0,
        "fg_pct": 42.7,
        "gp": 34,
        "team_abbr": "RGV"
      }
    },
    {
      "id": 1643019,
      "name": "Gabe Madsen",
      "position": "Forward",
      "team": "Sioux Falls Skyforce",
      "team_abbr": "SXF",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1643019.png",
      "headshot_local": "images/players/gabe-madsen.png",
      "ig": "gabemadsen",
      "stats": {
        "ppg": 9.4,
        "rpg": 5.0,
        "apg": 2.9,
        "fg_pct": 44.2,
        "gp": 39,
        "team_abbr": "SXF"
      }
    },
    {
      "id": 1628995,
      "name": "Kevin Knox II",
      "position": "Forward",
      "team": "Westchester Knicks",
      "team_abbr": "WCB",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628995.png",
      "headshot_local": "images/players/kevin-knox.png",
      "ig": "kevinknox",
      "stats": {
        "ppg": 22.3,
        "rpg": 7.9,
        "apg": 1.8,
        "fg_pct": 47.8,
        "gp": 30,
        "team_abbr": "WCB"
      }
    },
    {
      "id": 203506,
      "name": "Victor Oladipo",
      "position": "Guard",
      "team": "Wisconsin Herd",
      "team_abbr": "WIS",
      "headshot_nba": "https://cdn.nba.com/headshots/nba/latest/1040x760/203506.png",
      "headshot_local": "images/players/victor-oladipo.png",
      "ig": "victoroladipo",
      "stats": {
        "ppg": 14.0,
        "rpg": 4.4,
        "apg": 3.8,
        "fg_pct": 39.6,
        "gp": 26,
        "team_abbr": "WIS"
      }
    }
  ],
  "college": [
    {
      "name": "Devin Brown",
      "position": "Guard",
      "school": "Davidson",
      "type": "college",
      "espn_id": 5311849,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5311849.png",
      "headshot_local": "images/players/devin-brown.png",
      "ig": "_devinbrown",
      "stats": {
        "ppg": 6.3,
        "rpg": 3.1,
        "apg": 1.6,
        "fg_pct": 39.7,
        "gp": 27
      }
    },
    {
      "name": "Akai Fleming",
      "position": "Guard",
      "school": "Georgia Tech",
      "type": "college",
      "espn_id": 5101784,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5101784.png",
      "headshot_local": "images/players/akai-fleming.png",
      "ig": "akai.fleming",
      "stats": {
        "ppg": 9.7,
        "rpg": 3.2,
        "apg": 1.3,
        "fg_pct": 36.7,
        "gp": 27
      }
    },
    {
      "name": "Jaiden Glover-Toscano",
      "position": "Guard",
      "school": "Saint Joseph's",
      "type": "college",
      "espn_id": 5142608,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5142608.png",
      "headshot_local": "images/players/jaiden-glover-toscano.png",
      "ig": "jglove.11",
      "stats": {
        "ppg": 15.7,
        "rpg": 4.7,
        "apg": 1.1,
        "fg_pct": 41.5,
        "gp": 25
      }
    },
    {
      "name": "Meechie Johnson Jr.",
      "position": "Guard",
      "school": "South Carolina",
      "type": "college",
      "espn_id": 4710770,
      "headshot_espn": "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/4710770.png",
      "headshot_local": "images/players/meechie-johnson-jr.png",
      "ig": "meechie.1",
      "stats": {
        "ppg": 17.1,
        "rpg": 3.3,
        "apg": 4.3,
        "fg_pct": 42.0,
        "gp": 27
      }
    },
    {
      "name": "Kok Yat",
      "position": "Forward",
      "school": "",
      "type": "college",
      "headshot_local": "images/players/kok-yat.png",
      "ig": "tuloww.21",
      "stats": null
    },
    {
      "name": "Kayden Allen",
      "position": "Guard",
      "school": "Cincinnati Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Cincinnati",
      "headshot_local": "images/players/kayden-allen.jpg",
      "ig": "kaydenallennn",
      "stats": null
    },
    {
      "name": "Jaron Saulsberry",
      "position": "Forward",
      "school": "Ole Miss Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Ole Miss",
      "headshot_local": "images/players/jaron-saulsberry.jpg",
      "ig": "guard_upronny",
      "stats": null
    },
    {
      "name": "Gallagher Placide",
      "position": "Forward",
      "school": "Wake Forest Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Wake Forest",
      "headshot_local": "images/players/gallagher-placide.jpg",
      "ig": "gallagherplacide",
      "stats": null
    },
    {
      "name": "Gavin Placide",
      "position": "Forward",
      "school": "Wake Forest Commit",
      "type": "highschool",
      "class_year": 2026,
      "commitment": "Wake Forest",
      "headshot_local": "images/players/gavin-placide.jpg",
      "ig": "gavinplacide",
      "stats": null
    }
  ],
  "international": [
    {
      "name": "Kamar Baldwin",
      "position": "Guard",
      "team": "FC Bayern Munich",
      "league": "BBL / EuroLeague",
      "headshot_local": "images/players/kamar-baldwin.png",
      "ig": "kamar_baldwin",
      "stats": null
    },
    {
      "name": "Kobi Simmons",
      "position": "Guard",
      "team": "Saski Baskonia",
      "league": "Liga ACB / EuroLeague",
      "headshot_local": "images/players/kobi-simmons.png",
      "ig": "kobi_simmons2",
      "stats": null
    },
    {
      "name": "Brandon Goodwin",
      "position": "Guard",
      "team": "Shanghai Sharks",
      "league": "CBA",
      "headshot_local": "images/players/brandon-goodwin.png",
      "ig": "toughlay",
      "stats": null
    },
    {
      "name": "Kaiser Gates",
      "position": "Forward",
      "team": "UCAM Murcia",
      "league": "Liga ACB",
      "headshot_local": "images/players/kaiser-gates.png",
      "ig": "kaiserg_22",
      "stats": null
    },
    {
      "name": "Jakarr Sampson",
      "position": "Forward",
      "team": "Zhejiang Guangsha Lions",
      "league": "CBA",
      "headshot_local": "images/players/jakarr-sampson.png",
      "ig": "karrsampson14",
      "stats": null
    }
  ]
};
